service: xr-backoffice
runtime: nodejs18
instance_class: F2
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
    static_files: dist/xr-backoffice/\1
    upload: dist/xr-backoffice/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
  - url: /.*
    static_files: dist/xr-backoffice/index.html
    upload: dist/xr-backoffice/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
  - url: /
    static_files: dist/xr-backoffice/index.html
    upload: dist/xr-backoffice/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
      strict-transport-security: max-age=31536000
      x-frame-options: deny
      x-xss-protection: 1; mode=block
      X-Content-Type-Options: nosniff
      content-security-policy: "default-src 'self' 'unsafe-inline' data: https://get-profile-ehqivncgha-uc.a.run.app/get-profile/api/get-profile https://get-token-ehqivncgha-uc.a.run.app/get-token/api/get-token https://get-clients-ehqivncgha-uc.a.run.app/get-clients/api/get-clientshttps://post-client-ehqivncgha-uc.a.run.app/post-client/api/post-client https://get-company-ehqivncgha-uc.a.run.app/get-company/api/get-company https://get-domains-ehqivncgha-uc.a.run.app/get-domains/api/get-domains https://get-domain-type-ehqivncgha-uc.a.run.app/get-domain-type/api/get-domain-type https://post-domain-ehqivncgha-uc.a.run.app/post-domain/api/post-domain https://get-domain-grp-ehqivncgha-uc.a.run.app/get-domain-grp/api/get-domain-grp https://get-users-ehqivncgha-uc.a.run.app/get-users/api/get-all-users https://get-users-roles-ehqivncgha-uc.a.run.app/get-users-roles/api/get-users-roles https://get-roles-ehqivncgha-uc.a.run.app/get-roles/api/get-roles https://post-user-ehqivncgha-uc.a.run.app/post-user/api/post-user https://post-domain-grp-ehqivncgha-uc.a.run.app/post-domain-grp/api/post-domain-grp https://client-service-ehqivncgha-uc.a.run.app/client-service/api/put-client https://get-users-ehqivncgha-uc.a.run.app/get-users/api/get-all-users"