service: xr-backoffice
runtime: nodejs18
instance_class: F2

handlers:
  - url: /v1/login/.*  # Ruta para el servicio de login
    script: auto
    secure: always

  - url: /v1/client/.*  # Ruta para el servicio de client
    script: auto
    secure: always

  - url: /v1/user/.*  # Ruta para el servicio de user
    script: auto
    secure: always

  - url: /v1/role/.*  # Ruta para el servicio de role
    script: auto
    secure: always

  - url: /v1/group-company/.*  # Ruta para el servicio de group-company
    script: auto
    secure: always

  - url: /v1/company/.*  # Ruta para el servicio de company
    script: auto
    secure: always

  - url: /v1/domain-category/.*  # Ruta para el servicio de domain-category
    script: auto
    secure: always

  - url: /v1/service-category/.*  # Ruta para el servicio de service-category
    script: auto
    secure: always

  - url: /v1/domain/.*  # Ruta para el servicio de domain
    script: auto
    secure: always

  - url: /v1/subdomain/.*  # Ruta para el servicio de subdomain
    script: auto
    secure: always

  - url: /v1/service-company/.*  # Ruta para el servicio de service-company
    script: auto
    secure: always

  - url: /v1/provider/.*  # Ruta para el servicio de provider
    script: auto
    secure: always

  - url: /v1/contact/.*  # Ruta para el servicio de contact
    script: auto
    secure: always

  - url: /v1/report/.*  # Ruta para el servicio de report
    script: auto
    secure: always

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$  # Archivos estáticos
    static_files: dist/xr-backoffice/\1
    upload: dist/xr-backoffice/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
    secure: always

  - url: /.*  # Ruta para servir el archivo index.html
    static_files: dist/xr-backoffice/index.html
    upload: dist/xr-backoffice/index.html
    secure: always
    http_headers:
      Access-Control-Allow-Origin: "*"
      strict-transport-security: max-age=31536000
      x-frame-options: deny
      x-xss-protection: 1; mode=block
      X-Content-Type-Options: nosniff
<<<<<<< Updated upstream
      content-security-policy: "default-src 'self' 'unsafe-inline' data: https://xrisk-client-drzcbalp5q-uk.a.run.app/v1/client https://xrisk-company-drzcbalp5q-uk.a.run.app/v1/company https://xrisk-contact-drzcbalp5q-uk.a.run.app/v1/contact https://xrisk-domain-drzcbalp5q-uk.a.run.app/v1/domain https://xrisk-domain-category-drzcbalp5q-uk.a.run.app/v1/domain-category https://xrisk-group-company-drzcbalp5q-uk.a.run.app/v1/groupcompany https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/login https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/logout https://xrisk-provider-drzcbalp5q-uk.a.run.app/v1/provider https://xrisk-role-drzcbalp5q-uk.a.run.app/v1/role https://xrisk-subdomain-drzcbalp5q-uk.a.run.app/v1/subdomain https://xrisk-user-drzcbalp5q-uk.a.run.app/v1/user"

# Configuración de recursos
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

# Configuración de logs
logging:
  level: info
=======
      content-security-policy: "default-src 'self' 'unsafe-inline' data: https://xrisk-client-drzcbalp5q-uk.a.run.app/v1/client https://xrisk-company-drzcbalp5q-uk.a.run.app/v1/company https://xrisk-contact-drzcbalp5q-uk.a.run.app/v1/contact https://xrisk-domain-drzcbalp5q-uk.a.run.app/v1/domain https://xrisk-domain-category-drzcbalp5q-uk.a.run.app/v1/domain-category https://xrisk-group-company-drzcbalp5q-uk.a.run.app/v1/groupcompany https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/login https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/logout https://xrisk-provider-drzcbalp5q-uk.a.run.app/v1/provider https://xrisk-role-drzcbalp5q-uk.a.run.app/v1/role https://xrisk-subdomain-drzcbalp5q-uk.a.run.app/v1/subdomain https://xrisk-user-drzcbalp5q-uk.a.run.app/v1/user; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://xrisk-client-drzcbalp5q-uk.a.run.app https://xrisk-company-drzcbalp5q-uk.a.run.app https://xrisk-contact-drzcbalp5q-uk.a.run.app https://xrisk-domain-drzcbalp5q-uk.a.run.app https://xrisk-domain-category-drzcbalp5q-uk.a.run.app https://xrisk-group-company-drzcbalp5q-uk.a.run.app https://xrisk-login-drzcbalp5q-uk.a.run.app https://xrisk-provider-drzcbalp5q-uk.a.run.app https://xrisk-role-drzcbalp5q-uk.a.run.app https://xrisk-subdomain-drzcbalp5q-uk.a.run.app https://xrisk-user-drzcbalp5q-uk.a.run.app"
>>>>>>> Stashed changes
