service: xr-backoffice
runtime: nodejs18
instance_class: F2
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
    static_files: dist/xr-backoffice/\1
    upload: dist/xr-backoffice/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
  - url: /.*
    static_files: dist/xr-backoffice/index.html
    upload: dist/xr-backoffice/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
  - url: /
    static_files: dist/xr-backoffice/index.html
    upload: dist/xr-backoffice/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
      strict-transport-security: max-age=31536000
      x-frame-options: deny
      x-xss-protection: 1; mode=block
      X-Content-Type-Options: nosniff
      content-security-policy: "default-src 'self' 'unsafe-inline' data: https://xrisk-client-drzcbalp5q-uk.a.run.app/v1/client https://xrisk-company-drzcbalp5q-uk.a.run.app/v1/company https://xrisk-contact-drzcbalp5q-uk.a.run.app/v1/contact https://xrisk-domain-drzcbalp5q-uk.a.run.app/v1/domain https://xrisk-domain-category-drzcbalp5q-uk.a.run.app/v1/domain-category https://xrisk-group-company-drzcbalp5q-uk.a.run.app/v1/groupcompany https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/login https://xrisk-login-drzcbalp5q-uk.a.run.app/v1/login/auth/logout https://xrisk-provider-drzcbalp5q-uk.a.run.app/v1/provider https://xrisk-role-drzcbalp5q-uk.a.run.app/v1/role https://xrisk-subdomain-drzcbalp5q-uk.a.run.app/v1/subdomain https://xrisk-user-drzcbalp5q-uk.a.run.app/v1/user"