runtime: nodejs18
instance_class: F2
handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
    static_files: dist/x-risk-client/\1
    upload: dist/x-risk-client/(.*\.(js|css|png|jpg|jpeg|gif|ico|json|woff|woff2))$
  - url: /.*
    static_files: dist/x-risk-client/index.html
    upload: dist/x-risk-client/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
  - url: /
    static_files: dist/x-risk-client/index.html
    upload: dist/x-risk-client/index.html
    http_headers:
      Access-Control-Allow-Origin: "*"
      strict-transport-security: max-age=31536000
      x-frame-options: deny
      x-xss-protection: 1; mode=block
      X-Content-Type-Options: nosniff
      content-security-policy: "default-src 'self' 'unsafe-inline' data: https://get-profile-ehqivncgha-uc.a.run.app https://get-token-ehqivncgha-uc.a.run.app https://get-clients-ehqivncgha-uc.a.run.app https://post-client-ehqivncgha-uc.a.run.app https://get-company-ehqivncgha-uc.a.run.app https://get-domains-ehqivncgha-uc.a.run.app https://get-domain-type-ehqivncgha-uc.a.run.app https://post-domain-ehqivncgha-uc.a.run.app https://get-domain-grp-ehqivncgha-uc.a.run.app https://get-users-ehqivncgha-uc.a.run.app https://get-users-roles-ehqivncgha-uc.a.run.app https://get-roles-ehqivncgha-uc.a.run.app https://post-user-ehqivncgha-uc.a.run.app https://post-domain-grp-ehqivncgha-uc.a.run.app"