export const environment = {
    firebase: {
        projectId: "x-risk-qa",
        appId: "574871984926",
        storageBucket: "x-risk-qa.appspot.com",
        apiKey: "AIzaSyAh9JrcUBfjbCPmGB-J1IQ5hf-2JKzjrbQ",
        authDomain: "x-risk-qa.firebaseapp.com",
        messagingSenderId: "1084318886396",
    },
    channel: 1,
    getProfileUrl: "http://localhost:8086/get-profile/api/get-profile",
    getTokenUrl: "http://localhost:9000/get-token/api/get-token",
    getCompanyUrl: "http://localhost:8088/get-company/api/get-company",
    getClientUrl: "http://localhost:8082/get-clients/api/get-clients",
    postClientUrl: "http://localhost:8083/post-client/api/post-client",
    getDomainsUrl: "http://localhost:8086/get-domains/api/get-domains",
    getDomainTypeUrl: "http://localhost:8087/get-domain-type/api/get-domain-type",
    postDomainUrl: "http://localhost:8085/post-domain/api/post-domain",
    getDomainGrpUrl: "http://localhost:8084/get-domain-grp/api/get-domain-grp",
    getUsersUrl:"http://localhost:8089/get-users/api/get-all-users",
    getUsersRolesUrl: "http://localhost:8093/get-users-roles/api/get-users-roles",
    getRolesUrl: "http://localhost:8092/get-roles/api/get-roles",
    postUserUrl: "http://localhost:8094/post-user/api/post-user",
    getAllUsersUrl: "http://localhost:/get-users/api/get-all-users",
    postDomainGrpUrl: "http://localhost:/post-domain-grp/api/post-domain-grp",
    putClientUrl: "http://localhost:8082/client-service/api/put-client"


    // getProfileUrl: "https://get-profile-ehqivncgha-uc.a.run.app/get-profile/api/get-profile",
    // getTokenUrl: "https://get-token-ehqivncgha-uc.a.run.app/get-token/api/get-token",
    // getClientUrl: "https://get-clients-ehqivncgha-uc.a.run.app/get-clients/api/get-clients",
    // postClientUrl: "https://post-client-ehqivncgha-uc.a.run.app/post-client/api/post-client",
    // getCompanyUrl: "https://get-company-ehqivncgha-uc.a.run.app/get-company/api/get-company",
    // getDomainsUrl: "https://get-domains-ehqivncgha-uc.a.run.app/get-domains/api/get-domains",
    // getDomainTypeUrl: "https://get-domain-type-ehqivncgha-uc.a.run.app/get-domain-type/api/get-domain-type",
    // postDomainUrl: "https://post-domain-ehqivncgha-uc.a.run.app/post-domain/api/post-domain",
    // getDomainGrpUrl: "https://get-domain-grp-ehqivncgha-uc.a.run.app/get-domain-grp/api/get-domain-grp",
    // getUsersUrl:"https://get-users-ehqivncgha-uc.a.run.app/get-users/api/get-all-users",
    // getUsersRolesUrl: "https://get-users-roles-ehqivncgha-uc.a.run.app/get-users-roles/api/get-users-roles",
    // getRolesUrl: "https://get-roles-ehqivncgha-uc.a.run.app/get-roles/api/get-roles",
    // postUserUrl: "https://post-user-ehqivncgha-uc.a.run.app/post-user/api/post-user",
    // getAllUsersUrl: "http://34.42.207.23/get-users/api/get-all-users",
    // postDomainGrpUrl: "https://post-domain-grp-ehqivncgha-uc.a.run.app/post-domain-grp/api/post-domain-grp",


};
